### ISSUE TITLE
Feature-request: add a whitelist within the censor function.

### ISSUE THREAD

**Issue by dgsus** [blargbot/blargbot#38]
hi,

it would be great if we could add a whitelist option to the censor function, for example i have a regex blocking any URL to be posted , but i wish i could whitelist a few websites so people could still post URL's that are deemed to be from safe domains. So i would whitelist for example www.cnn.com and any posts that a user (which is not on a role added to the exceptions list) could still post a news article from cnn.com.

thank you in advance!
D

**Comment by HunteRoi** [comment]
@Ratismal @danny-may How do you guys see that on the current version of the bot? I might take a look at implementing it during next month.

**Comment by Saederup92** [comment]
Whitelist as in a per user basis like with a per role basis or am I misunderstanding?

**Comment by HunteRoi** [comment]
At the beginning, I thought it would be a kind of global censor whitelisting system... But after reading the request again, I think @dgsus only needs to edit their regex blocking all URLs in order to allow certain domains _they_ define as _safe domains_, which is something that is already achievable with the current system (thanks RegEx 😄).

And, after another deep read just to be sure, I think that introducing "a whitelist option" in the current version of the command means rework the whole command because this is no more the same point of view.

**Comment by HunteRoi** [comment]
Although I think about a flag that could stand as a regex with a whitelist option editable through that same flag at the creation of the censorship and through a subcommand when the censorship is already created.

Something belong the lines of 
```
b!t censor ADD -W https://cnn.com
```
with flag `-W` or `--whitelist` meaning that the censorship triggers on _every message containing an URL_ if the matched URLs are not in the provided whitelist. No argument would mean the whitelist is empty for that guild so every message with an URL triggers the censor.

**Comment by danny-may** [comment]
I dont think this is an issue that we can really fix. Censors arent blocking urls only, theyre blocking any pattern you give. If you want to add an exclusion to your regex, you could try to use a negative lookbehind in your regex
